title = "项目配置文件"

[server]
port = 8089

[postgres]
host = "192.168.2.210:5432"
username = "admin"
password = "123456"
db = "postgres"
max_open_conns = 500
max_idle_conns = 50
log = true

[redis]
host = "127.0.0.1:6379"
password = ""

[kafka]
broker = "192.168.1.15:9092"
